NewResponsee:

<NewResponsee>:
    name : "main"
    mycket_missnojd: mycket_missnojd
    missnojd: missnojd
    nojd: nojd
    mycket_nojd: mycket_nojd
    bar_data: bar_data
    pie_data: pie_data

    min_label: min_label

    spacing: 50
    padding: 20
    rows: 2
    
    Label:
        id: min_label
        text: "Hur var dagens lektion?"
        color: 0,0,0
        font_size: 48
        size_hint: (1, .20)
        # on_release: root.animate_it(self)


    BoxLayout:
        cols: 2
        size_hint: (1, .20)

        Label: 
            text: ""

        Button:
            id: mycket_missnojd
            background_color: 0,0,0,0
            size_hint: (1,1)
            on_press: root.mycket_missnojd_on()
            on_release: root.mycket_missnojd_off()
            on_release: root.knapp_tryck(self)
            
            Image:
                id: mycket_missnojd_bilden
                source: "arg.png"
                center_x: self.parent.center_x
                center_y: self.parent.top

        Button:
            id: missnojd
            background_color: 0,0,0,0
            on_press: root.missnojd_on()
            on_release: root.missnojd_off()
            on_release: root.knapp_tryck(self)
            Image:
                id: missnojd_bilden
                source: "missnojd.png"
                center_x: self.parent.center_x
                center_y: self.parent.top      

        Button:
            id: nojd
            background_color: 0,0,0,0
            on_press: root.nojd_on()
            on_release: root.nojd_off()
            on_release: root.knapp_tryck(self)
            Image:
                id: nojd_bilden
                source: "nojd.png"
                center_x: self.parent.center_x
                center_y: self.parent.top

        Button:
            id: mycket_nojd
            background_color: 0,0,0,0 
            on_press: root.mycket_nojd_on()
            on_release: root.mycket_nojd_off()
            on_release: root.knapp_tryck(self)
            Image:
                id: mycket_nojd_bilden
                source: "mycket nojd.png"
                center_x: self.parent.center_x
                center_y: self.parent.top

        

        BoxLayout:
            orientation: 'vertical'
            RoundedButton:

                id: bar_data
                text: "Visa data (Bar Chart)"
                font_size: 12
                on_press: root.knapp_tryck(self)
                
                size_hint: (None, None)
                width: 120
                height: 60
            
            
            
            RoundedButton:

                id: pie_data
                text: "Visa data (Pie Chart)"
                font_size: 12
                
                on_press: root.knapp_tryck(self)
                # on_press: root.visa()
                size_hint: (None, None)
                width: 120
                height: 60


<RoundedButton@Button>
    background_color: (0,0,0,0)
    background_normal: ""
    canvas.before:
        Color:
            rgba: (17/255,14/255,214/255,0.99)
        RoundedRectangle:
            size: self.size
            pos: self.pos
            radius: [10] # omkring rektangel
